name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # Setup Python
    - name: Set up Python
      uses: actions/setup-python@v4

    # Install cookiecutter
    - name: Install and Run Cookiecutter
      run: |
        pip install cookiecutter
        cookiecutter . --no-input
        ls -la

    # Create and Activate Conda Env
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: test-env
        environment-file: a-cookiecutter-repository-for-quarto/environment.yml

    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2

    # Install Tex Deps
    - run: |
        sudo apt-get install \
          texlive-xetex \
          texlive-fonts-recommended \
          texlive-plain-generic

    # Build Project
    - name: Build webpage
      shell: bash -l {0}
      run: |
        cd a-cookiecutter-repository-for-quarto/
        just build